42ity/nut

- drivers/mge-xml.c
Left the old code in place, commented away. If devices with old NetXML pop up (those which served in XML 10x the measured value), fixes can be applied based on voltage and amps and power (order of magnitude comparison), or perhaps model names and/or firmware versions or release dates, if we get those.
Note: trivial but practical testing with at least modern devices (e.g. descendent Eaton UPS models) is still needed ATM.
> Disable convert_deci() that was needed a decade ago

- drivers/eaton-pdu-marlin-mib.c
- drivers/snmp-ups.c
- scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
Solution: shuffle the order in MIB file. Publish the value.
> Problems: Eaton G3 ePDU outlet.%i.name overwritten by fallback entry; device.count==1 not published

- drivers/eaton-pdu-marlin-mib.c
- scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
Add support for shutdown and start timers
> eaton-pdu-marlin-mib.c/dmf: add outlet timers

- drivers/eaton-ats16-mib.c
- drivers/mge-mib.c
- drivers/mge-xml.c
- drivers/powerware-mib.c
- scripts/DMF/dmfsnmp/eaton-ats16-mib.dmf
- scripts/DMF/dmfsnmp/mge-mib.dmf
- scripts/DMF/dmfsnmp/powerware-mib.dmf
Add support for the 2 GPI accessible through EMP001 environmental sensor,
connected to a UPS or ATS16. The same is already available for Eaton ePDU.
This affect the snmp-ups driver (eaton_ats16 and pw/pxgx_ups MIBs), and the
netxml-ups driver
> Add support for dry contacts to Eaton ATS16 and UPS

- drivers/eaton-ats16-mib.c
- drivers/eaton-pdu-marlin-mib.c
- drivers/mge-mib.c
- drivers/mge-xml.c
- drivers/powerware-mib.c
- scripts/DMF/dmfsnmp/eaton-ats16-mib.dmf
- scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
- scripts/DMF/dmfsnmp/mge-mib.dmf
- scripts/DMF/dmfsnmp/powerware-mib.dmf
While "open" is the best adjective for the opposite of "closed", and thus
suitable for GPI status, this may lead to confusion with the GPO actions
"open|close" Vs the GPI status "opened|closed". These last are also not
inapropriate, since they can refer to the fact that the GPI state has change
due to some external action or event
> Modify "open" to "opened" for dry contacts status

- common/common.c
- docs/configure.txt
- docs/man/nutupsdrv.txt
- docs/man/upsd.txt
- drivers/main.c
> Support envvar for ALTPIDPATH with documentation

- drivers/snmp-ups.c
Solution:  base_snmp_template_index() prevented from processing empty argument
Signed-off-by: Barbora Stepankova <BarboraStepankova@eaton.com>
> Problem: snmp-ups segfaults

- docs/man/Makefile.am
- drivers/snmp-ups.c
These have been upstreamed too, where applicable.
> Fix cross-branch merge errors missed some months ago

- server/upsd.c
(cherry picked from commit f7d80a29610a43c08e43c9db1c7bca7c051c3c1a)
> upsd should return EXIT_FAILURE when -c failed

- scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
Minimize the chance that this happens by comparing the config file early in the startup of the script and just before it is done reconfiguring things. This way, while a window for missing a change still remains (and would get picked up by a re-run e.g. with asset-republish processing), it would be sub-second rather than a much longer configuration period we face now.
> Problem: nut-driver-enumerator can miss changes of ups.conf happening WHILE it runs

- configure.ac
- docs/config-notes.txt
- scripts/Solaris/nut-driver-enumerator.xml.in
- scripts/systemd/.gitignore
- scripts/systemd/Makefile.am
- scripts/systemd/README
- scripts/systemd/nut-driver-enumerator-daemon-activator.path.in
- scripts/systemd/nut-driver-enumerator-daemon-activator.service.in
- scripts/systemd/nut-driver-enumerator-daemon.service.in
- scripts/systemd/nut-driver-enumerator.path.in
- scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
Try a more robust solution to problem tackled in #69 by addressing potential issues, and also wrapping the daemonized mode as a service.
Follow-ups to use it after this is merged should include:
* fty-nut : tickling `nut-driver-enumerator-daemon.service` rather than `nut-driver-enumerator.service` in fty-nut reconfiguration script, to request a re-evaluation cycle ASAP
* fty-core : when preparing the OS image, make sure to enable just one implementation of the service bundle (they are marked to conflict)
> Support nut-driver-enumerator-daemon systemd service

- drivers/eaton-pdu-marlin-helpers.c
since the value reading is always adapted to celsius
> SNMP Eaton ePDU: always return celsius for temperature

- drivers/nut-libfreeipmi.c
- drivers/powerware-mib.c
- drivers/rhino.c
- scripts/DMF/dmfsnmp/powerware-mib.dmf
* fix reading of input.voltage, related to the ending ".0",
* fix existing commands handling,
* add support for the load segment (managed outlets), including
status information and commands
> SNMP Eaton Gb Network Card: various data completion

- scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
This should fix a noted problem that a newly initialized deployment tries for some time and fails to start `nut-server.service`. If the tests were quick to detect some power devices before this retry timeout, or if the system is restarted after configurations were made, the service is started and problem is not seen.
However if some time passes and systemd gives up trying to start the nut-server unit, and *then* the ups.conf entries appear, the NDE service configures the nut-driver unit instances but does not restart-or-reload nut-server because it is not known active or starting. This fix adds "failed" to the filter, so a not-disabled dead nut-server would be "re-"started when configs change (or appear in this case).
Another commit addresses the warning from systemd regarding start-up of …
> Hotfix nut-driver-enumerator.sh.in (42ity FTY)

- drivers/eaton-ats16-mib.c
- drivers/eaton-ats16-mib.h
- drivers/snmp-ups.c
- scripts/DMF/dmfnutscan/dmfnutscan-snmp.dmf
- scripts/DMF/dmfsnmp/eaton-ats16-mib.dmf
Add support for Eaton ATS16 using the new Network-M2 communication cards,
and including a fixed sysOID fingerprint
(cherry picked from commit 88c79e245038e1cad9debd46f725016147bd5474)
Also update DMF files
> snmp-ups: add Eaton ATS16 with new Network-M2

- conf/nut.conf.sample
- conf/upsd.conf.sample
- docs/man/upsd.conf.txt
- scripts/augeas/nutupsdconf.aug.in
- scripts/augeas/tests/test_nut.aug
- server/conf.c
- server/upsd.c
- server/upsd.h
Follow-up from #102 
Tested to support different ways of spelling the boolean setting in upsd.conf and in envvar as supported (and with higher priority) per original PR.
> Allow to configure ALLOW_NO_DEVICE (nee NUT_NOCONF_ALLOWED) option via upsd.conf

- drivers/main.c
NUT drivers in dump mode are now crashing with buffer overflows unless this specific section of code is reverted:
```
admin@eaton-rc-0050568CAEA8:~$ /lib/nut/snmp-ups -s test -d 2 -x port=10.130.32.120
Network UPS Tools - Generic SNMP UPS driver (DMF) 1.14 (2.7.4.1)
Detected Eaton 9PX 8000i on host 10.130.32.120 (mib: pw 0.98)
*** buffer overflow detected ***: /lib/nut/snmp-ups terminated
Aborted
admin@eaton-rc-0050568CAEA8:~$ 
```
This has been root-caused to a faulty modification of dump mode logic.
> Fix faulty dump mode logic

- drivers/eaton-pdu-marlin-mib.c
- scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
Use a hack to also have switchability for both the unit and its
outlets on legacy Eaton G2 ePDU
> snmp-ups: Restore legacy Eaton ePDU switchability info

- drivers/eaton-pdu-marlin-mib.c
- scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
Use a hack to also have switchability for both the unit and its
outlets on legacy Eaton G2 ePDU
(cherry picked from commit 79ccdf08377ee3a4c698ecf2eee0ac69fcacb9d3)
> snmp-ups: Restore legacy Eaton ePDU switchability info (2.2.0)

- drivers/snmp-ups.c
Instants commands using numeric parameters, like on/off/cycle
commands, were failing due to a bad value submitted type (time
instead of integer)
Ref: IPMVAL-2198
> snmp-ups: fix instant commands using numeric parameters

- drivers/snmp-ups.c
Instants commands using numeric parameters, like on/off/cycle
commands, were failing due to a bad value submitted type (time
instead of integer)
(cherry picked from commit 62816819cb1e5270f6b17eb5c55ad0429866a1b7)
Ref: IPMVAL-2198
> [2.2.0] snmp-ups: fix instant commands using numeric parameters

- drivers/eaton-pdu-marlin-mib.c
- scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
Fix a regression that caused a mis-determination of the SNMP base
OID index (0 or 1, should be 1). This in turn caused a mis-iteration
over the outlets, from 0 to N-1 instead of 1 to N, which resulted in
the missing Nth outlet (last outlet of the PDU). This also caused some
data refresh issues
> snmp-ups: fix regression on Eaton ePDU

- Jenkinsfile
- docs/config-prereqs.txt
- docs/nut.dict
- scripts/DMF/Makefile.am
- scripts/DMF/dmfify-mib.sh
- scripts/DMF/dmfsnmp/apc-ats-mib.dmf
- scripts/DMF/dmfsnmp/apc-mib.dmf
- scripts/DMF/dmfsnmp/compaq-mib.dmf
- scripts/DMF/dmfsnmp/cyberpower-mib.dmf
- scripts/DMF/dmfsnmp/eaton-ats16-nm2-mib.dmf
- scripts/DMF/dmfsnmp/eaton-ats16-nmc-mib.dmf
- scripts/DMF/dmfsnmp/eaton-ats30-mib.dmf
- scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
- scripts/DMF/dmfsnmp/eaton-pdu-pulizzi-mib.dmf
- scripts/DMF/dmfsnmp/hpe-pdu-mib.dmf
- scripts/DMF/dmfsnmp/huawei-mib.dmf
- scripts/DMF/dmfsnmp/ietf-mib.dmf
- scripts/DMF/dmfsnmp/mge-mib.dmf
- scripts/DMF/dmfsnmp/powerware-mib.dmf
- scripts/DMF/dmfsnmp/raritan-px2-mib.dmf
- scripts/DMF/jsonify-mib.py.in
- scripts/DMF/nut_cpp
- scripts/DMF/xmlify-mib.py.in
Follows up from #135, #137, #138 and that those CI checks missed the changed MIB files that should have been in sync with DMF files.
Also, it seems that newer python3 and/or pycparser does not sort the XML entries for DMF the same way our code did with python2 (alphabetically inside entries). Probably need to add some more options to some call. Under investigation...
UPDATE: Indeed, somewhere around Python 3.6 and 3.8, return of values from dictionaries became not sorted but per original population of values; so explicit sorting is needed as we want reproducible XMLs with minimal diffs over time. This PR now also fixes lookup table orders, which was quite mixed in earlier saved DMF files.
> Jenkinsfile: fix detection of "GitIgnores good after make" (shell exit-code, groovy quotes for evaluation)

- drivers/eaton-pdu-marlin-mib.c
- drivers/powerware-mib.c
- scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
- scripts/DMF/dmfsnmp/powerware-mib.dmf
Following the recent addition of the "String reformating function"
(su_find_strval()), a regression appeared on a corner case: when
flagging a data with ST_FLAG_STRING, while the SNMP OID is an int,
and when there is a fun_vp2s() conversion function, a double
conversion is applied, resulting in no value published. This was
limited to one data (temperature.unit)
> Fix regression on Eaton EMP002 temperature reading (SNMP)

- drivers/eaton-ats16-nm2-mib.c
- scripts/DMF/dmfsnmp/eaton-ats16-nm2-mib.dmf
This support is identical to what is in Eaton Marlin
and Powerware MIBs. Future improvements should consider
putting these bits in a common eaton-sensor-mib file,
to avoid multiple definition of the same MIB structure!
> Eaton: add support for EMP002 on ATS16 NM2 with SNMP

- drivers/powerware-mib.c
- scripts/DMF/dmfsnmp/powerware-mib.dmf
Though there is output.Lx.power.percent, for 3phase,
it's desirable to also have the standard ups.load
> Eaton SNMP: also publish ups.load for 3phase

- drivers/snmp-ups.c
- tools/nut-scanner/scan_snmp.c
See also networkupstools#1267
Thanks @stark-dev for noticing the strange run-time behavior.
> tools/nut-scanner/scan_snmp.c, drivers/snmp-ups.c: fix match of shorter "SHA" and "AES" (42ity)

- common/dmfsnmp.c
- drivers/powerware-mib.c
- drivers/snmp-ups.c
- drivers/snmp-ups.h
- scripts/DMF/dmfsnmp.xsd
- scripts/DMF/dmfsnmp/apc-mib.dmf
- scripts/DMF/dmfsnmp/baytech-mib.dmf
- scripts/DMF/dmfsnmp/bestpower-mib.dmf
- scripts/DMF/dmfsnmp/compaq-mib.dmf
- scripts/DMF/dmfsnmp/cyberpower-mib.dmf
- scripts/DMF/dmfsnmp/eaton-ats16-nm2-mib.dmf
- scripts/DMF/dmfsnmp/eaton-pdu-genesis2-mib.dmf
- scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
- scripts/DMF/dmfsnmp/eaton-pdu-pulizzi-mib.dmf
- scripts/DMF/dmfsnmp/eaton-pdu-revelation-mib.dmf
- scripts/DMF/dmfsnmp/emerson-avocent-pdu-mib.dmf
- scripts/DMF/dmfsnmp/hpe-pdu-mib.dmf
- scripts/DMF/dmfsnmp/huawei-mib.dmf
- scripts/DMF/dmfsnmp/ietf-mib.dmf
- scripts/DMF/dmfsnmp/mge-mib.dmf
- scripts/DMF/dmfsnmp/netvision-mib.dmf
- scripts/DMF/dmfsnmp/powerware-mib.dmf
- scripts/DMF/dmfsnmp/raritan-pdu-mib.dmf
- scripts/DMF/dmfsnmp/xppc-mib.dmf
- scripts/DMF/jsonify-mib.py.in
- scripts/DMF/xmlify-mib.py.in
- tools/nut-scanner/scan_snmp.c
Sibling to https://github.com/networkupstools/nut/pull/1180 with adaptations for new DMF-related flags and scripts.
Work in progress to see how that impacts build and run-time behavior.
> Redefine bit-flag map values for snmp-ups.h in DMF/FTY codebase
