drivers/mge-xml.c
Make a debug notice for end-users, and bump subdriver version for clarity.
=> Complete the MGE-XML deprecation of decimation

drivers/eaton-ats16-mib.c, scripts/DMF/dmfsnmp/eaton-ats16-mib.dmf, scripts/systemd/Makefile.am
Mainly ports "snmp-ups: ATS16 fixes for ambient sensor values" fix into DMF reality
=> FTY update from upstream master and DMF branches

configure.ac, docs/Makefile.am, docs/man/Makefile.am, drivers/eaton-mib.c, drivers/openups-hid.c, m4/nut_check_asciidoc.m4, scripts/DMF/dmfsnmp/eaton-mib.dmf, tools/gitlog2changelog.py
Checking it is still green in clean env :)
=> FTY branch resync from master as of 2017-08-02

drivers/eaton-pdu-marlin-mib.c, scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
Signed-off-by: Jim Klimov <EvgenyKlimov@eaton.com>
=> Fix typo in OID, noticed by aquette

drivers/snmp-ups.c, drivers/snmp-ups.h
Problem : In convergence, IPM needs location & contact from ePDU
Solution : https://github.com/networkupstools/nut/pull/320
Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>
=> snmp-ups: add sysContact and sysLocation support

.travis.yml, common/dmfsnmp.c, drivers/eaton-pdu-marlin-helpers.c, drivers/eaton-pdu-marlin-helpers.h, drivers/eaton-pdu-marlin-mib.c, drivers/snmp-ups.c, drivers/snmp-ups.h, include/dmfsnmp.h, scripts/DMF/dmfsnmp.xsd, scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf, scripts/DMF/jsonify-mib.py, scripts/DMF/xmlify-mib.py
The skeleton for solution, ATM just with added values, to start experimenting against real hardware, picking data-types, etc. Ultimately need to update DMF files too - not done so far.
No-merge note: SNMP mapping data types may be wrong, segfaults might not be a surprise.
=> Support Eaton ePDU G3 new firmware OIDs

drivers/eaton-pdu-marlin-mib.c
Solution: Attach 1 feed to the current input
=> Problem: Need to fix published feed variables

docs/man/Makefile.am
docs/man/Makefile.am : rearrange MAN3_DEV_PAGES so that nutclient_*.3 can be built even with parallel build
=> Fix parallel builds of NUT

scripts/DMF/Makefile.am, scripts/DMF/dmfify-mib.sh, scripts/DMF/jsonify-mib.py, tools/Makefile.am
Merge, rebase PR #28 and it should work in Travis well now.
=> Repair DMF "jsonify" parser for PR #28 usecase

drivers/eaton-pdu-marlin-helpers.c, drivers/eaton-pdu-marlin-helpers.h, drivers/eaton-pdu-marlin-mib.c, scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf, scripts/DMF/testdata-fun/eaton-pdu-marlin-mib_WITH_SNMP_LKP_FUN_DUMMY.dmf
=> snmp-ups: simplify Eaton ePDU group phase handling

tools/nut-scanner/nut-scan.h, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/scan_eaton_serial.c, tools/nut-scanner/scan_nut.c, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_xml_http.c
Signed-off-by: barraudl <lilianbarraud@eaton.com>
=> Add thread limitation to avoid memory error

scripts/DMF/.gitignore, tools/nut-scanner/nutscan-device.c, tools/nut-scanner/nutscan-display.c, tools/nut-scanner/nutscan-ip.c, tools/nut-scanner/nutscan-ip.h, tools/nut-scanner/scan_eaton_serial.c, tools/nut-scanner/scan_ipmi.c, tools/nut-scanner/scan_nut.c, tools/nut-scanner/scan_usb.c, tools/nut-scanner/scan_xml_http.c
Solution: use TABs where 8-SPACEs were
=> Problem: Indentation varies in nut-scanner sources

tools/nut-scanner/README, tools/nut-scanner/nut-scan.h, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/nutscan-init.c, tools/nut-scanner/nutscan-init.h
Signed-off-by: barraudl <lilianbarraud@eaton.com>
=> Fix the Debian package generation

drivers/eaton-pdu-marlin-mib.c, scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
=> snmp-ups: Eaton feed color is semi static

scripts/DMF/jsonify-mib.py
=> DMF/jsonify-mib.py: support for int and hexa values

m4/nut_check_libavahi.m4, m4/nut_check_libneon.m4
Mostly a resync of commits present here and there with different hashes
=> Bump FTY branch from opensource/master

drivers/eaton-pdu-marlin-mib.c, drivers/snmp-ups.c, scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
Equivalent to https://github.com/networkupstools/nut/pull/681
=> Fix snmp templates (FTY)

common/common.c
Thanks to @EldoreiJK for helping notice this. Equivalent upstreamed at https://github.com/networkupstools/nut/pull/708
=> BUILD_64 merged twice and not detected in some distros

scripts/Solaris/nut-driver.xml.in, scripts/systemd/nut-driver@.service.in
Backport of #88 into pending release
=> Problem: Attempts to start a nut-driver@bogusname... (2.0.0)

drivers/eaton-pdu-marlin-mib.c, drivers/powerware-mib.c, scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf, scripts/DMF/dmfsnmp/powerware-mib.dmf
Sensor may not be present (or connected). However, the values
(temperature, humidity, ...) are still available, but should not be
considered
=> SNMP Eaton EMP002: handle sensor presence

drivers/snmp-ups.c
=> Fix false positive when communication is lost

drivers/apc-ats-mib.c, drivers/ietf-mib.c, scripts/DMF/dmfnutscan/dmfnutscan-snmp.dmf, scripts/DMF/dmfsnmp/apc-ats-mib.dmf, tools/nut-scanner/scan_snmp.c, tools/nut-snmpinfo.py
CAUTION: Not for IPM winter realease.
It will be merged after winter release delivery.
=> Fix nutscan snmp

scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
=> Hotfix nut-driver-enumerator.sh.in (42ity 2.1.0)

docs/nut-names.txt, drivers/eaton-pdu-marlin-mib.c, scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
This includes:
* improved visibility on whole-unit and per-outlet switchability visibility
* fix on outlet identifier
=> snmp-ups: Eaton ePDU outlet management improvements

drivers/eaton-pdu-marlin-mib.c, drivers/powerware-mib.c, scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf, scripts/DMF/dmfsnmp/powerware-mib.dmf
=> Fix dry contacts status for EMP02 (2.3.0)

drivers/eaton-pdu-marlin-mib.c, drivers/powerware-mib.c, scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf, scripts/DMF/dmfsnmp/powerware-mib.dmf
fix dry contacts status  for emp02
=> Pqswmbt 4637 fix dry contacts status (FTY main branch)

Jenkinsfile-dynamatrix, ci_build.sh, docs/ci-farm-lxc-setup.txt, docs/config-prereqs.txt
Should not impact 42ity builds at the moment, but would ease eventual upstreaming of DMF.
=> Jenkinsfile-dynamatrix: align upstream Python-versions testing with DMF concerns

Jenkinsfile
=> Jenkinsfile: Using a milestone step inside parallel is not allowed

ci_build.sh, docs/config-prereqs.txt, docs/nut.dict, drivers/mge-xml.c, drivers/snmp-ups.c
...and a few small fixes on top of earlier merges #154 et al
=> FTY remerge from upstream NUT as of 2021-11-22

NEWS, UPGRADING, data/driver.list.in, docs/acknowledgements.txt, docs/config-prereqs.txt, docs/man/nutdrv_qx.txt, docs/nut.dict, docs/nutdrv_qx-subdrivers.txt, drivers/Makefile.am, drivers/nutdrv_qx.c, drivers/nutdrv_qx_ablerex.c, drivers/nutdrv_qx_ablerex.h
Yet another bump in upstream, mostly commemorating the "NEWS" of recent changes (merged driver PRs etc)
=> FTY remerge from upstream NUT as of 2022-01-23
